#!/usr/bin/env php
<?php

/** @var \Egal\Core\Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

$server = new \Swoole\HTTP\Server(
    env('SWOOLE_HTTP_HOST', '0.0.0.0'),
    (int) env('SWOOLE_HTTP_PORT', 8080)
);

$server->on(
    'start',
    function (\Swoole\Http\Server $server) {
        echo 'Http server is started!' . PHP_EOL;
    }
);

$server->on(
    'request',
    function (\Swoole\Http\Request $swooleRequest, \Swoole\Http\Response $swooleResponse) use ($app) {
        \App\SwooleSymfonyBridge\Response::writeSwooleResponse(
            $swooleResponse,
            $app->handle(\App\SwooleSymfonyBridge\Request::createFromSwooleRequest($swooleRequest))
        );
    }
);

$server->start();
