name: Release notify
on:
  release:
    types:
      - published
jobs:
  release-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: egal/release-notify-action@main
        with:
          repository_name: ${{ github.repository }}
          release_json: ${{ toJson(github.event.release) }}
          telegram_channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID_FOR_RELEASE_NOTIFY }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
